### ISSUE TITLE
finesse llamaindex index experiment

### ISSUE THREAD

**Issue by leejaeka** [ai-cfia/llamaindex-db#10]
[Diagram](https://www.canva.com/design/DAF98lCu0bw/VuJqgcp6fYDbjGocv7EhWw/edit?utm_content=DAF98lCu0bw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Compare different types of llamaindex indexes (vectorindex, treeindex, listindex, keywordindex) performance on subset (2500 cluster) of finesse data. Evaluate accuracy and runtime.

![Search evaluation](https://github.com/ai-cfia/llamaindex-db/assets/538542/0bafc7cd-272a-4fc5-991e-7b7332e8c2f9)

**Comment by rngadam** [comment]
took the liberty to download a PNG and insert it into the description

**Comment by ibrahim-kabir** [comment]
> took the liberty to download a PNG and insert it into the description

I see it as more of an epic rather than just a simple . Each stage of the plan appears to represent a distinct issue."

**Comment by rngadam** [comment]
@ibrahim-kabir spend a bit more time breaking this work and other tasks with @leejaeka to ensure collaboration is visible and can be reviewed by @nmeraihi

**Comment by ibrahim-kabir** [comment]
@leejaeka, from my understanding this work is finished. Could you update this issue with your discoveries and comments ? Afterwards change the status to done.

**Comment by leejaeka** [comment]
Other index of llamaindex, other than vectorstoreindex took far too long (30seconds+)
